import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { trpc } from "@/lib/trpc";
import { BookOpen, CalendarDays, Check, ChevronDown, Clock3, History, Pause, Play, Plus, RotateCcw, Sparkles, Target, Timer, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const formatTime = (totalSeconds: number) => `${String(Math.floor(Math.max(0, totalSeconds) / 3600)).padStart(2, "0")}:${String(Math.floor((Math.max(0, totalSeconds) % 3600) / 60)).padStart(2, "0")}:${String(Math.max(0, totalSeconds) % 60).padStart(2, "0")}`;
const statusLabel: Record<string, string> = { planned: "Planejada", accepted: "Aceita", in_progress: "Em andamento", completed: "Concluída", postponed: "Adiada", cancelled: "Cancelada" };

function Frame({ children }: { children: React.ReactNode }) { return <div className="page-frame"><div className="page-heading"><div><p className="eyebrow">Execução</p><h1 className="display-title">Flows</h1><p className="body-copy mt-2 max-w-2xl">Entre em foco, registre o tempo real e acompanhe seu ritmo sem transformar estudo em cobrança.</p></div></div>{children}</div>; }

function SelectionModal({ blocks, exams, sessions, onSelectBlock, onSelectExam, onClose }: { blocks: any[]; exams: any[]; sessions: any[]; onSelectBlock: (id: number) => void; onSelectExam: (id: number) => void; onClose: () => void }) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={event => event.target === event.currentTarget && onClose()}><div className="modal-card flow-picker" role="dialog" aria-modal="true" aria-labelledby="flow-picker-title"><div className="section-row"><div><p className="eyebrow">Contexto do Flow</p><h2 id="flow-picker-title" className="card-title mt-1">O que você vai estudar?</h2></div><button className="icon-button" onClick={onClose} aria-label="Fechar"><X size={18} /></button></div><div className="flow-picker-section mt-6"><div className="section-row"><div><p className="eyebrow">Executáveis</p><p className="caption mt-1">Blocos planejados e provas abertas</p></div><span className="status-pill status-lilac">{blocks.length + exams.length}</span></div><div className="picker-list mt-3">{blocks.map(block => <button key={`block-${block.id}`} className="picker-row" onClick={() => onSelectBlock(block.id)}><div className="icon-bubble bubble-lilac"><CalendarDays size={16} /></div><div className="min-w-0 flex-1 text-left"><p className="font-semibold truncate">{block.title}</p><p className="caption mt-1">{block.durationMinutes} min · {statusLabel[block.status]}</p></div><ChevronDown className="-rotate-90" size={16} /></button>)}{exams.map(exam => <button key={`exam-${exam.id}`} className="picker-row" onClick={() => onSelectExam(exam.id)}><div className="icon-bubble bubble-mint"><Target size={16} /></div><div className="min-w-0 flex-1 text-left"><p className="font-semibold truncate">{exam.name}</p><p className="caption mt-1">{exam.institution} · sessão avulsa</p></div><Plus size={16} /></button>)}{!blocks.length && !exams.length && <div className="compact-empty"><Target size={18} /><p className="caption">Cadastre uma prova ou gere um plano antes de iniciar.</p></div>}</div></div><div className="flow-picker-section mt-6"><div className="section-row"><div><p className="eyebrow">Histórico recente</p><p className="caption mt-1">Referência, não um novo contexto executável</p></div><History size={17} className="text-[var(--edu-text-secondary)]" /></div>{sessions.length ? <div className="history-list mt-3">{sessions.slice(0, 4).map(session => <div key={session.id} className="history-row"><span className="history-dot" /><div className="min-w-0"><p className="font-semibold">Sessão concluída</p><p className="caption mt-1">{session.actualMinutes ?? 0} min · {new Date(session.startedAt).toLocaleDateString("pt-BR")}</p></div><Check size={15} className="text-[var(--edu-mint-strong)]" /></div>)}</div> : <p className="caption mt-3">Suas sessões finalizadas aparecerão aqui.</p>}</div></div></div>;
}

function FlowTimerCard({ active, selectedLabel, onChoose, onPause, onResume, onComplete, onCancel }: { active: any; selectedLabel?: string; onChoose: () => void; onPause: () => void; onResume: () => void; onComplete: () => void; onCancel: () => void }) {
  const [liveSeconds, setLiveSeconds] = useState(active?.elapsedSeconds ?? 0);
  useEffect(() => { setLiveSeconds(active?.elapsedSeconds ?? 0); }, [active?.session?.id, active?.elapsedSeconds]);
  useEffect(() => { if (!active || active.session.status !== "running") return; const interval = window.setInterval(() => setLiveSeconds((current: number) => current + 1), 1000); return () => window.clearInterval(interval); }, [active?.session?.id, active?.session?.status]);
  const running = active?.session.status === "running";
  const paused = active?.session.status === "paused";
  return <section className="soft-card flow-timer-card"><div className="section-row"><div><p className="eyebrow">Flow ativo</p><button className="flow-context-button mt-2" onClick={onChoose}>{active?.block?.title || selectedLabel || "Escolher contexto"}<ChevronDown size={15} /></button></div><button className="icon-button" onClick={onChoose} aria-label="Escolher sessão ou prova"><Target size={18} /></button></div><div className={cn("timer-display", running && "is-running", paused && "is-paused")}><div className="timer-glow" /><span>{formatTime(liveSeconds)}</span><small>{running ? "em foco agora" : paused ? "pausado com segurança" : "pronto para começar"}</small></div><div className="flow-timer-actions">{!active ? <Button className="soft-button-primary w-full" onClick={onChoose}><Target size={16} /> Escolher sessão ou prova</Button> : running ? <><Button className="soft-button-secondary flex-1" onClick={onPause}><Pause size={16} /> Pausar</Button><Button className="soft-button-primary flex-1" onClick={onComplete}><Check size={16} /> Finalizar</Button></> : <><Button className="soft-button-primary flex-1" onClick={onResume}><Play size={16} /> Retomar</Button><Button variant="outline" className="soft-button-secondary" onClick={onCancel} aria-label="Cancelar Flow"><X size={16} /></Button></>}</div><p className="caption text-center mt-4">Você pode sair desta página. O Flow continua salvo.</p></section>;
}

function FlowChart({ series, isLoading }: { series: any[] | undefined; isLoading: boolean }) {
  const hasData = series?.some(day => day.minutes > 0);
  return <section className="soft-card flow-chart-card"><div className="section-row"><div><p className="eyebrow">Tempo em movimento</p><h2 className="card-title mt-1">Seu ritmo nos últimos 7 dias</h2></div><div className="chart-legend"><span /> minutos</div></div><div className="flow-chart mt-5">{isLoading ? <div className="chart-empty"><Timer className="animate-pulse" size={20} /></div> : hasData ? <ResponsiveContainer width="100%" height="100%"><LineChart data={series} margin={{ top: 15, right: 12, bottom: 0, left: -20 }}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: "var(--edu-text-secondary)", fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "var(--edu-text-secondary)", fontSize: 10 }} allowDecimals={false} /><Tooltip contentStyle={{ borderRadius: 12, border: "1px solid var(--border)", background: "var(--card)", color: "var(--edu-text-primary)" }} formatter={(value) => [`${value} min`, "Estudo"]} /><Line type="monotone" dataKey="minutes" stroke="var(--edu-purple-strong)" strokeWidth={3} dot={{ r: 3, fill: "var(--edu-purple-strong)", strokeWidth: 0 }} activeDot={{ r: 5 }} /></LineChart></ResponsiveContainer> : <div className="chart-empty"><Clock3 size={22} /><div><p className="font-semibold">A linha começa com sua primeira sessão</p><p className="caption mt-1">Finalize um Flow para ver o tempo virar uma tendência.</p></div></div>}</div><div className="flow-chart-footer"><span><strong>{series?.reduce((sum, day) => sum + day.minutes, 0) ?? 0} min</strong> nesta janela</span><span>histórico concluído</span></div></section>;
}

export default function Flows() {
  const [location, setLocation] = useLocation();
  const { data: dashboard, isLoading: dashboardLoading } = trpc.dashboard.useQuery();
  const activeQuery = trpc.flows.active.useQuery(undefined, { refetchInterval: 1000 });
  const seriesQuery = trpc.flows.series.useQuery({ days: 7 });
  const utils = trpc.useUtils();
  const [pickerOpen, setPickerOpen] = useState(false);
  const [selectedLabel, setSelectedLabel] = useState("");
  const start = trpc.flows.start.useMutation({ onSuccess: async () => { await utils.flows.active.invalidate(); await utils.dashboard.invalidate(); setPickerOpen(false); } });
  const createAdHoc = trpc.flows.createAdHoc.useMutation({ onSuccess: result => { start.mutate({ blockId: result.id }); } });
  const pause = trpc.flows.pause.useMutation({ onSuccess: () => utils.flows.active.invalidate() });
  const resume = trpc.flows.resume.useMutation({ onSuccess: () => utils.flows.active.invalidate() });
  const complete = trpc.flows.complete.useMutation({ onSuccess: async () => { await utils.flows.active.invalidate(); await utils.flows.series.invalidate(); await utils.dashboard.invalidate(); } });
  const cancel = trpc.flows.cancel.useMutation({ onSuccess: async () => { await utils.flows.active.invalidate(); await utils.flows.series.invalidate(); await utils.dashboard.invalidate(); } });
  const queryBlock = new URLSearchParams(location.split("?")[1] ?? "").get("block");
  const queryExam = new URLSearchParams(location.split("?")[1] ?? "").get("exam");
  useEffect(() => { if (queryBlock && dashboard?.blocks.some(block => block.id === Number(queryBlock))) setSelectedLabel(dashboard.blocks.find(block => block.id === Number(queryBlock))?.title ?? ""); }, [queryBlock, dashboard?.blocks]);
  useEffect(() => { if (queryExam && dashboard?.exams.some(exam => exam.id === Number(queryExam))) setSelectedLabel(dashboard.exams.find(exam => exam.id === Number(queryExam))?.name ?? ""); }, [queryExam, dashboard?.exams]);
  const active = activeQuery.data;
  const executableBlocks = useMemo(() => (dashboard?.blocks ?? []).filter(block => ["planned", "accepted", "in_progress"].includes(block.status)), [dashboard?.blocks]);
  const activeExams = useMemo(() => (dashboard?.exams ?? []).filter(exam => exam.status === "active"), [dashboard?.exams]);
  if (dashboardLoading) return <Frame><div className="soft-card p-12 grid place-items-center"><Timer className="animate-pulse" /></div></Frame>;
  const chooseBlock = (id: number) => start.mutate({ blockId: id });
  const chooseExam = (id: number) => createAdHoc.mutate({ examId: id });
  return <Frame><div className="flow-intro"><div className="flow-intro-badge"><Sparkles size={15} /> foco possível</div><p>Selecione um contexto, comece pelo tempo que você tem e deixe o histórico mostrar o caminho.</p></div><div className="flows-grid mt-5"><FlowTimerCard active={active} selectedLabel={selectedLabel} onChoose={() => setPickerOpen(true)} onPause={() => active && pause.mutate({ id: active.session.id })} onResume={() => active && resume.mutate({ id: active.session.id })} onComplete={() => active && complete.mutate({ id: active.session.id })} onCancel={() => active && cancel.mutate({ id: active.session.id })} /><FlowChart series={seriesQuery.data} isLoading={seriesQuery.isLoading} /></div>{(start.error || createAdHoc.error || pause.error || complete.error) && <div className="inline-error mt-4"><RotateCcw size={15} /> {start.error?.message.includes("ACTIVE_FLOW") ? "Você já tem um Flow ativo. Finalize ou pause antes de iniciar outro." : "Não foi possível atualizar este Flow. Tente novamente."}</div>}{pickerOpen && <SelectionModal blocks={executableBlocks} exams={activeExams} sessions={(dashboard?.sessions ?? []).filter(session => session.status === "completed")} onSelectBlock={chooseBlock} onSelectExam={chooseExam} onClose={() => setPickerOpen(false)} />}<div className="flow-support-grid mt-5"><div className="soft-card p-6"><div className="icon-bubble bubble-blue"><BookOpen size={17} /></div><h2 className="card-title mt-4">Um Flow não precisa ser perfeito</h2><p className="body-copy mt-2">Se você tiver 25 minutos, use 25. O valor está em registrar o que realmente aconteceu.</p></div><div className="soft-card p-6"><div className="icon-bubble bubble-mint"><Check size={17} /></div><h2 className="card-title mt-4">Histórico sem culpa</h2><p className="body-copy mt-2">Sessões concluídas entram no Painel e ajudam a tornar sua evolução concreta.</p></div></div></Frame>;
}
